### ISSUE TITLE
Linux: only reloads once

### ISSUE THREAD

**Issue by sliceofcode** [leovoel/BeautifulDiscord#10]
When saving the file, BeautifulDiscord reloads the CSS file once. Subsequent file changes are not applied to Discord.

**Comment by sliceofcode** [comment]
This has something to do with `fs.watch`, because doing `applyAndWatchCSS` re-applies the stylesheet and reloads once again.

The first (and only) reload triggers these events:

```
rename dsc.css
change dsc.css
rename dsc.css
rename dsc.css 
```

**Comment by sliceofcode** [comment]
Okay, turns out this had to do with `writebackup` being enabled in Vim. This messes with `fs.watch`. `set nowritebackup` fixes this. Closed.

**Comment by leovoel** [comment]
yeah, it's a common issue. maybe i should toss a warning about it somewhere.

**Comment by magiruuvelvet** [comment]
A lot of programs do this, they save to a separate file and rename it afterwards.

Examples of editors I use:
 - Qt Creator
 - KWrite/Kate

This is annoying, nothing that can be fixed on the Node.js file system watcher side.

**Comment by sliceofcode** [comment]
`fs.watchFile` can apparently fix this, but it is slower, unreliable, and uses `stat`s.
