### ISSUE TITLE
python 3.6.0 and psutil latest verion

### ISSUE THREAD

**Issue by XCanG** [leovoel/BeautifulDiscord#12]
Can you update your lib? I can't install older psutil on python 3.6.0 and it not work with latest psutil library.

**Comment by magiruuvelvet** [comment]
Everything works perfectly fine with everyting on the latest verstion. Just hack the dependency file. The psutil version compatibility given here is wrong.

```diff
--- BeautifulDiscord/requirements.txt	2017-01-08 13:25:35.616506571 +0100
+++ BeautifulDiscord/requirements.txt.fix	2017-01-08 13:25:59.093173587 +0100
@@ -1 +1 @@
-psutil==4.3.1
+psutil>=4.3.1
```

---

Python 3.6
psutil 5.0.1

**Comment by Rapptz** [comment]
The version is pinned in case of breaking changes. As it stands, there are none currently so doing this is fine.

**Comment by leovoel** [comment]
i bumped it up in 4129c71, cheers
