### ISSUE TITLE
Python version conflict or psutil not found

### ISSUE THREAD

**Issue by Omnak** [leovoel/BeautifulDiscord#13]
I'm on Manjaro Linux and installed BeautifulDiscord via the aur but I'm getting a crash that seems to either be related to Python versioning or to BeautifulDiscord not finding psutils.

```
$ beautifuldiscord
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 5.0.1 (/usr/lib/python3.6/site-packages), Requirement.parse('psutil==5.1.0'), {'BeautifulDiscord'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/beautifuldiscord", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil==5.1.0' distribution was not found and is required by BeautifulDiscord](url)
```

```
$ python --version
Python 3.6.0
$ yaourt psutil
1 extra/psutils 1.17-5 [installed]
2 community/python-psutil 5.0.1-2 [installed]
```

I'd guess that BeautifulDiscord is just not looking in the right directory for Python, but I went and checked, and it is looking in exactly the right place. Are the aur packages maybe not up to date, or does BeautifulDiscord maybe prefer an older version of something? Or am I completely wrong about all of the above and have no idea what's happening?

**Comment by leovoel** [comment]
there's a version mismatch there, this expects `psutil 5.1.0` while you have `5.0.1`.

currently psutil is pinned so i don't have to deal with their breaking changes, but maybe it's fine to just not pin it. i'll probably do that in a bit.

**Comment by Omnak** [comment]
Ah, so the aur packages are definitely outdated :/

I'll be looking forward to being able to use this in the meantime. I've been wishing the Discord UI was more compact for a while, this would finally give me the ability to do something about it.

**Comment by syl3nt** [comment]
well, for me aur package is way to ahead ahahah , i am on
2 community/python-psutil 5.2.2-1 [installed]
    A cross-platform process and system utilities module for Python
3 community/python2-psutil 5.2.2-1 [installed]
    A cross-platform process and system utilities mod..

**Comment by syl3nt** [comment]
i think i might have found a solution, like me, you are running arch, you can install with yaourt, 'yaourt downgrade' and its the [2 aur/downgrade 5.4.0-1 [installed] (420) (7.56)
    Bash script for downgrading one or more packages to a version in your cache or the A.R.M.] for me, and then , after install you just do 'downgrade python-util', it lists all the previous versions and you install the 5.1.0 , i believe that that is the requirement

**Comment by syl3nt** [comment]
yes, it's working 100% :-)

**Comment by leovoel** [comment]
i have unpinned psutil in 81e5805. it should fix your installation issue (although compatibility issues with psutil are possible now, but i doubt they'll be severe).

i'm closing this, but if you want it reopened, just comment again here.
