### ISSUE TITLE
Question: How is this called?

### ISSUE THREAD

**Issue by lordjbs** [leovoel/BeautifulDiscord#18]
How is this bar called?
![coo](https://cloud.githubusercontent.com/assets/23281889/23331072/56811daa-fb5e-11e6-8cc5-b718a509123a.PNG)

**Comment by leovoel** [comment]
the "bar" is separated in two parts. on the left, the container class is called `guild-header` and on the right it's `title-wrap`.

you can press ctrl+shift+i and click on the first button to the left, then you can hover over most of these and find out what they are easily.
