### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by RjGunner111** [leovoel/BeautifulDiscord#20]
https://gyazo.com/6c48669e9331ff32cadf869838b89368 as i type in "python -m beautifuldiscord", it gives me this error. I have also noticed this message as well: https://gyazo.com/2bf93fd59465b95ca4fafc7e67afc08b if there is a solution for this, please reply to this comment.

**Comment by Rapptz** [comment]
Your Python installation looks broken.

**Comment by RjGunner111** [comment]
never mind, i fixed it. turned out i wasn't in the recent version of python.
