### ISSUE TITLE
BeautifulDiscord on Arch Linux

### ISSUE THREAD

**Issue by kevr** [leovoel/BeautifulDiscord#29]
On Arch Linux, the discord directory is located at `/opt/discord`, the binary is named `Discord` -- When running beautifuldiscord, it is unable to locate the discord binary. Also, it tries to create things in the directory, but it is installed as a system program, so I have to change permissions in order to do that which is not necessarily good. Perhaps something in $XDG_CONFIG_HOME should be used?

**Comment by Lastrik** [comment]
Personnaly if found that beautifuldiscord is working. You just need to have discord open when running beautifuldiscord and run beautifuldiscord as root.

**Comment by GNUGradyn** [comment]
chown /opt/discord to you, works fine

**Comment by Rapptz** [comment]
This should be fixed now since it doesn't require writing in any directory except writeable directories.
