### ISSUE TITLE
Error when Discord starts at Windows boot

### ISSUE THREAD

**Issue by brussell98** [leovoel/BeautifulDiscord#3]
If Discord is set to start when Windows starts it will attempt to load the custom CSS from `system32/`.
This causes an error preventing Discord from loading.

**Comment by leovoel** [comment]
are you up to date?
if you open `%localappdata%\Discord[PTB | Canary]\app-x.x.xx\resources\app\cssInjection.js`, what's the last line that you see? it should be something like `window.applyAndWatchCSS(absolute path to stylesheet);`

**Comment by brussell98** [comment]
It says `window.applyAndWatchCSS('./discord-custom.css');`
This can be fixed by add the `--css "path here"` arg but is not documented

**Comment by leovoel** [comment]
oh, right, the default path isn't absolute. i'll fix that and also mention the `--css` flag on the readme as it's better than shoving a file in discord's install path

**Comment by leovoel** [comment]
31221f2 fixes this issue for the default css location and 4e6981b adds more info on the readme.
thanks for the report.
