### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by heyitswither** [leovoel/BeautifulDiscord#30]
I'm all of the sudden (after it working fine) getting a `[Errno 2] No such file or directory` error when I try to use beautifuldiscord. `beautifuldiscord --help` works just fine, but -css and --revert give the error. I have reinstalled beautifuldiscord with nothing changing.

**Comment by aequasi** [comment]
getting the same thing

**Comment by iFonny** [comment]
me too

**Comment by Rapptz** [comment]
This should be fixed.
