### ISSUE TITLE
Not working after latest Discord update?

### ISSUE THREAD

**Issue by scotbud123** [leovoel/BeautifulDiscord#31]
Hi,

Was just noticing how after today's update, BD doesn't seem to even attempt to load, and nothing CSS wise is functioning whatsoever. Am I the only one suffering from this issue, or is there something that needs to be updated?

Thanks in advance!

**Comment by XElectricX** [comment]
Same here. I miss my theme. The file is still untouched, and restarting Discord does not make it load. 😭

**Comment by leovoel** [comment]
i cannot reproduce this on stable, ptb, or canary. the application files are still extracted, and the code is injected correctly.

if you are talking about your themes being broken, that's not really something this program can fix.

**Comment by Glassglow** [comment]
I am also having this issue. BeautifulDiscord appears to be installed, but no CSS is loaded. Is there any way to check if the location for the .css file changed?

**Comment by brussell98** [comment]
When the Discord client moves to a new version number you need to re-run BD

**Comment by XElectricX** [comment]
@brussell98 Can you elaborate? How would one re-run it?

**Comment by brussell98** [comment]
`python3 -m beautifuldiscord` in my case

**Comment by scotbud123** [comment]
@brussell98 I tried that and it seemed to work:

https://i.imgur.com/W5xcYMh.png

However, Discord acted the same way upon being restarted, still doesn't seem to make a simple attempt to load the CSS file whatsoever.

**Comment by scotbud123** [comment]
Alright, so I figured out the main source of this issue...

Discord made a new sub-folder under the "\AppData\Local\Discord\" directory in Windows with this update, and the new .css file was blank, I just had to update that and it worked like a charm. Such a simple fix, makes me feel silly for making such a huge oversight.

Thanks for the help anyways everyone!

**Comment by XElectricX** [comment]
Yeah, I spent like a couple of hours trying to make it work until I paid close attention to the command prompt after running `python -m beautifuldiscord` like @brussell98 suggested. New directory where the .css file goes should be under:

`C:\Users\[username]\AppData\Local\Discord\app-0.0.298\resources\discord-custom.css`

Just have to copy and paste the file to there. Should work like a charm again. 😄

**Comment by leovoel** [comment]
as a reminder, you probably should be using the [`--css` flag](https://github.com/leovoel/BeautifulDiscord#usage) instead, which allows you to pick a more convenient location for your stylesheet
