### ISSUE TITLE
[macOS error] Process still exist but it's a zombie

### ISSUE THREAD

**Issue by retke** [leovoel/BeautifulDiscord#34]
Hey, I managed to install betterdiscord on my MacBook, as I'm used to Linux, which works a bit like macOS terminal. But when I'm starting betterdiscord, I get this *quite unique* error:

```
MacBook-Pro-of-Laggron:~ laggron$ beautifuldiscord --css betterdiscord/prism.css
psutil.ZombieProcess process still exists but it's a zombie (pid=1395)
```

I searched the error but it seems it's code related, so maybe I can get some help here about that

**Comment by Rapptz** [comment]
This should be fixed.
