### ISSUE TITLE
"failed to create process" error

### ISSUE THREAD

**Issue by JoeBanks13** [leovoel/BeautifulDiscord#4]
I keep getting a "failed to create process" error whenever I try use `beatifuldiscord -css [my file]`

I'm on Windows 10 using command line.

My discord version is Canary Updated yesterday (27/09/16)

**Comment by lgn-drk** [comment]
Use `--css`, not `-css`.

**Comment by JoeBanks13** [comment]
Yeah fixed now @lgn-drk I tried, `python -m beautifuldiscord --css discord.css` and it worked

**Comment by lgn-drk** [comment]
Please close your issue.

**Comment by lgn-drk** [comment]
Thank you @Rapptz.
