### ISSUE TITLE
Doesn't work with discord as of Jan 8th

### ISSUE THREAD

**Issue by TacticAlpha** [leovoel/BeautifulDiscord#40]
When attempting to install theme it gives the following error `FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'` in `app.py` , tested on normal release and PTB, worked fine before the update that I just got for both.
  
edit: I also uninstalled and reinstalled this to make sure it was up to date before testing.

**Comment by leovoel** [comment]
did you try the canary branch?
```
python3 -m pip install -U https://github.com/leovoel/BeautifulDiscord/archive/canary.zip
```

(reminds me that the readme should be updated)

**Comment by TacticAlpha** [comment]
Yes that works, I didn't think to try other branches. Thanks!
