### ISSUE TITLE
Repacking asar

### ISSUE THREAD

**Issue by rauenzi** [leovoel/BeautifulDiscord#43]
Hey there, saw in the commit [here](https://github.com/leovoel/BeautifulDiscord/commit/f87144e42e02ab87fd58f94fbd714b0b738eac3d), that you repack the asar after modifying `mainScreen.js`. This shouldn't be necessary if you modify the `index.js` at `%appdata%\discord\x.x.xxx\modules\discord_desktop_core` to be `module.exports = require('./core');` instead of `module.exports = require('./core.asar');`. I have been doing this and not had any issues with discord since the modules are still imported properly.

**Comment by Rapptz** [comment]
When I tested out that change initially it didn't work so I considered it too finicky to be used at a larger scale for more people.

**Comment by rauenzi** [comment]
Fair enough, I haven't had any reports about it from any BetterDiscord or BandagedBD users (where we use that method) hopefully the issue you had was a one-time fluke. I only mentioned it because I saw the comment in commit complained about repack being slow.

(Love your API wrapper by the way)
