### ISSUE TITLE
Cannot Revert Changes

### ISSUE THREAD

**Issue by BakaTekku** [leovoel/BeautifulDiscord#44]
![capture](https://user-images.githubusercontent.com/28825262/35434550-69b20944-023c-11e8-88cc-ac8f481e1cc6.PNG)
It doesn't seem to be extracting the app.asar file as I'm missing the extracted app folder and the
original_app.asar file.

So invoking the script with the --revert flag will do nothing. it might be overwriting the original app.asar file.

**Comment by leovoel** [comment]
the script doesn't touch `app.asar` anymore, it now looks in `%appdata%\discord\x.x.xxx\modules\discord_desktop_core\core.asar` (it still follows the same pattern of keeping a `original_XXXX.asar` file).

can you take a look there?

**Comment by BakaTekku** [comment]
Oh I see, The Readme for the manual method still shows the old location might want to update that.
I can confirm it does indeed keep an original_core.asar file and I can successfully revert changes manually.

However the --revert flag still fails to automatically accomplish this even on a fresh discord install.

**Comment by leovoel** [comment]
updated the readme. `--revert` should also be fixed, let me know if it isn't
