### ISSUE TITLE
Fatal javascript error on fresh install

### ISSUE THREAD

**Issue by DoYouPikachu** [leovoel/BeautifulDiscord#45]
![image](https://user-images.githubusercontent.com/16530766/35775335-b42b1866-093b-11e8-9fda-810e02c64d86.png)
Fresh discord install, after applying the beautifuldiscord css hot reload to it. 
Python version 3.4
psutil installed already

**Comment by leovoel** [comment]
can't reproduce this on canary or stable. maybe you have an old version of this script? otherwise i have no idea what could be happening here

**Comment by DoYouPikachu** [comment]
Traced down the issue to psutil not working with Python 3.4 and upgrading to Python 3.5 instead.
