### ISSUE TITLE
Suggestion: Linux .deb, .run, or .app file?

### ISSUE THREAD

**Issue by PrismaticYT** [leovoel/BeautifulDiscord#54]

**Comment by SparrowOchon** [comment]
Since Discord is updated from within itself there is no difference in what you chose in terms of updates. For management sake, it is recommended you use `.deb`

**Comment by kot83** [comment]
Why not use pip to install?

**Comment by simoniz0r** [comment]
pip is not a clean way to install software on Linux ever.

**Comment by ArsenArsen** [comment]
Why not? Just put it in a virtualenv and remove it when you're done, if you really care. otherwise simply `pip3 install --user ...`.
