### ISSUE TITLE
Discord's CSS assets overwriting custom CSS

### ISSUE THREAD

**Issue by SamuiNe** [leovoel/BeautifulDiscord#58]
Hello hello o/

Just a note, I have already updated beautifuldiscord to latest version, deleted the AppData\Roaming\discord folder, and reinstalled discord.

Lately with the recent Discord update, custom CSS seems to be occasionally getting overwritten by Discord's CSS assets. The one time custom CSS works, it can be broken again with Ctrl + R or when Discord is restarted. I'm not quite sure what causes this, but I hope this would be fixed soon.

Here is the image just in case-
![Discord CSS asset overwriting the custom CSS](https://i.imgur.com/rGh2R9r.png)

Thank you in advance!

**Comment by Rapptz** [comment]
I can't repro this. Use [`!important`](https://stackoverflow.com/a/9245360/1381108).
