### ISSUE TITLE
External style sheets blocked again :/

### ISSUE THREAD

**Issue by GriffinG1** [leovoel/BeautifulDiscord#59]

**Comment by Pierce01** [comment]
Seems to still work for me. 

could you post your console?

**Comment by CodyMKW** [comment]
still works fine for me on Windows 7

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/44295940-2e300e80-a268-11e8-8e54-e957e56ae222.png)

**Comment by Pierce01** [comment]
make sure you're using the latest BeautifulDiscord, since it seems to be working on Discord Canary (0.0.211) and Discord Stable (0.0.301)

**Comment by GriffinG1** [comment]
curious.. it showed i had the latest version of beautifuldiscord, however it seems like it was mistaken? idk, it's fixed now however.
