### ISSUE TITLE
--insecure flag for insecure features (local imports and local images)

### ISSUE THREAD

**Issue by polyjitter** [leovoel/BeautifulDiscord#7]
Of course, default behavior should definitely be to be as secure as possible; however, this also comes with the side effect of the inability to use local resources. When a resource is ~8MB, it may be preferable to use i t locally.

For people who desire these feature, at the cost of Electron security, a flag for such features could be helpful.

**Comment by leovoel** [comment]
i don't have any strong opinions on this besides the fact that it's quite the slippery slope.

anyway, for reference,
http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions
the `webSecurity` option in the `webPreferences` object is what needs to be changed.
