### ISSUE TITLE
"This is awkward" error on all recent canary builds

### ISSUE THREAD

**Issue by TheSqrtMinus1** [leovoel/BeautifulDiscord#73]
Hi! As of a while ago I'm getting this error upon injecting beautifuldiscord with discord canary. It injects successfully (hence the colored background) but it then pops up with this error: 

![image](https://user-images.githubusercontent.com/15315481/60697293-9a832300-9eb7-11e9-8018-0a43f53ef126.png)

This happened for me months ago as well, but I stopped using canary so I didn't report it. I switched (tried to switch) back and it gives me this error.

is there any fix for this ?

**Comment by Rapptz** [comment]
I cannot reproduce this issue on build 40795

**Comment by SparrowOchon** [comment]
Can you please provide additional details such as script output and discord canary version ?

**Comment by TheSqrtMinus1** [comment]
fixed, disregard. guess after the 6th uninstall/reinstall of canary it worked. 🤷

**Comment by Artuto** [comment]
I'm having this very issue and I cannot make it work
