### ISSUE TITLE
css_injection_path broken on Windows

### ISSUE THREAD

**Issue by EArmour** [leovoel/BeautifulDiscord#79]
With the change in PR #78, `os.path.join(os.getenv('XDG_CACHE_HOME', '~/.cache'), 'beautifuldiscord)` expands on Windows machines (which obviously don't have `XDG_CACHE_HOME` set) to something like `C:\Users\Username/.cache\beautifuldiscord`, which ain't right.

**Comment by Rapptz** [comment]
Windows should be capable of handling both / and \ as a path separator so I don't see the issue. I tried this on Windows 8.1 and can confirm there is no issue too.

**Comment by EArmour** [comment]
That doesn't seem to be the case for me. This is with Python 3.7.5, copying the code from app.py exactly except changing the env variable since I already set it to get the install to work:

```
>>> import os
>>> css_injection_path = os.path.expanduser(os.path.join(os.getenv('NONEXISTENT', '~/.cache'), 'beautifuldiscord'))
>>> os.mkdir(css_injection_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Evan/.cache\\beautifuldiscord'
>>> print(css_injection_path)
C:\Users\Evan/.cache\beautifuldiscord
```

Even if it is 'supposed' to work and possibly does for some configuration, it's just bad practice to have explicit path separators inside a call to `os.path.join`, because then what's the point of using the library joining method if you're joining paths manually inside of it anyways?

**Comment by EArmour** [comment]
Upon looking further, I think the actual root issue is calling `os.mkdir` on a path that now by default is two levels deep. If you don't already have a `.cache` directory in user home, the `mkdir` will fail. Using `os.makedirs` instead with the same argument succeeds by creating the intermediate `.cache` directory as well. Either way, a normal Windows installation does not include a premade `.cache` folder in the home directory, so the script will fail every time.
