### ISSUE TITLE
Fail to inject on latest (at the time) Discord PTB

### ISSUE THREAD

**Issue by PythonTryHard** [leovoel/BeautifulDiscord#89]
*Steps to recreate*:

0. Get a Ubuntu machine running (actual environment is `KDE neon` but Ubuntu should be fine)
1. Download Discord, PBT branch, version 0.20.0. Install fresh, log in.
2. Perform installation as instructed in `README.md`
3. Inject custom CSS as instructed in `README.md`

*Expected behavior*:
`beautifuldiscord` exits with code 0, custom CSS shows normally.

*Actual behavior*:
`beautifuldiscord` exit with code 0, custom CSS is not shown. While verifying both `index.js` in `discord.script_path` and `mainWindows.js` inside the new `core.asar` shows that the injection is indeed successful, Developer Tools > Sources does not show any trace of the custom CSS.

Affected version:
- Discord PTB (latest, Ubuntu)
- Discord Canary (latest, Ubuntu)

**Comment by Rapptz** [comment]
Try PR #88

**Comment by PythonTryHard** [comment]
Tested on PTB 0.21.0 because I forgot to check my GitHub. Had to restore the original state of `index.js` and `core.asar`, but other than that, the injector worked again.
