### ISSUE TITLE
Broken in latest update

### ISSUE THREAD

**Issue by BanchouBoo** [leovoel/BeautifulDiscord#90]
The core.asar file is successfully modified, but the css never loads in Discord. There is an error in the injected js file, seen below.
![image](https://user-images.githubusercontent.com/32691832/89567356-7fd45980-d7ef-11ea-9ec4-eb0a46ea27dc.png)

**Comment by LinkofHyrule89** [comment]
So far I can't get BD to work with the newest Discord on Linux either so not sure what broke it.

**Comment by Rapptz** [comment]
This should be fixed in master. There was a PR to fix this in #88 but it's been merged now since it's now in general availability.
